---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go
    tag: 'latest'

inputs:
- name: gnatsd
  path: gopath/src/github.com/nats-io/gnatsd

run:
  path: gopath/src/github.com/nats-io/gnatsd/ci/tasks/test.sh